export const ProductCategory = [
  {
    id: "all",
    label: "All",
  },
  {
    id: "PL/TAB/001",
    label: "Tablets",
  },
  {
    id: "PL/CAP/002",
    label: "Capsules",
  },
  {
    id: "PL/LOZ/003",
    label: "Lozenges",
  },
  {
    id: "PL/BAL/004",
    label: "Balm",
  },
  {
    id: "PL/INH/005",
    label: "Inhaler",
  },
  {
    id: "PL/SAC/006",
    label: "Sachets",
  },
  {
    id: "PL/SYR/007",
    label: "Oral Liquids",
  },
  {
    id: "PL/OIL/008",
    label: "Oils",
  },
  {
    id: "PL/OIN/009",
    label: "Ointments",
  },
  // {
  //     id: "PL/POW/006",
  //     label: "Powders"
  // },
  // {
  //     id: "PL/CRE/007",
  //     label: "Creams"
  // },
];

export const ComprehensiveProductList = [
  {
    id: 1,
    productName: "Strome Active Balm",
    uses: "Painkiller, Headache, Body Ache	",
    pack: "10 ml bottle	",
    packSize: "Mono Carton",
  },
  {
    id: 2,
    productName: "Brocough HT syrup	",
    uses: "Bronchodialator",
    pack: "Bottle Pack	",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 3,
    productName: "Hepa99 syrup	",
    uses: "Liver Tonic",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 4,
    productName: "Honicad syrup	",
    uses: "Cough Syrup	",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 5,
    productName: "lactavari syrup	",
    uses: "Lactative Syp	",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 6,
    productName: "Megaliv syrup	",
    uses: "Vitalilazer",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 7,
    productName: "Nephri syrup	",
    uses: "helps in kidney cleanse	",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 8,
    productName: "Purifin syrup	",
    uses: "Blood Purifier syrup	",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 9,
    productName: "Sufliv syrup",
    uses: "Liver Tonic",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 10,
    productName: "Uticare syrup	",
    uses: "Uterine Tonic",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 11,
    productName: "Xtaplate Syrup",
    uses: "To Increase PlateletS count	",
    pack: "Bottle Pack",
    packSize: "200 ml , 100 ml",
  },
  {
    id: 12,
    productName: "Asholiv capsules	",
    uses: "liver tonic",
    pack: "Carton",
    packSize: "10 x 10 Alu PVC Blister",
  },
  {
    id: 13,
    productName: "Softlora Tablet",
    uses: "Natural Laxative	",
    pack: "Carton",
    packSize: "10 x 10 Alu PVC Blister",
  },
  {
    id: 14,
    productName: "Brainlyf Tablet",
    uses: "Brain Tonic	",
    pack: "Carton",
    packSize: "10 x 10 Alu PVC Blister",
  },
  {
    id: 15,
    productName: "Deityca Tablet",
    uses: "Immunity Booster",
    pack: "Carton",
    packSize: "10 x 10 Alu PVC Blister",
  },
  {
    id: 16,
    productName: "Fit Frack capsules",
    uses: "Usefull to cure bone fracture",
    pack: "Carton",
    packSize: "10 x 10 Alu PVC Blister",
  },
  {
    id: 17,
    productName: "Urja capsules	",
    uses: "Revitilizer",
    pack: "Carton",
    packSize: "10 x 10 Alu PVC Blister",
  },
  {
    id: 18,
    productName: "LoseSafe Tablet",
    uses: "Laxative",
    pack: "Carton",
    packSize: "10 x 10 Alu PVC Blister",
  },
  {
    id: 19,
    productName: "Nephry Capsules",
    uses: "Kidney stone",
    pack: "Carton",
    packSize: "10 x 10 Alu PVC Blister",
  },
  {
    id: 20,
    productName: "Falldown hair oil	",
    uses: "Reduce Hair fall	",
    pack: "Fliptop bottle",
    packSize: "100 ml",
  },
  {
    id: 21,
    productName: "Strome Active Inhaler",
    uses: "de-congestant",
    pack: "Inheler",
    packSize: "with/without keychain",
  },
  {
    id: 22,
    productName: "Suhani breast cream",
    uses: "Breast Firming cream	",
    pack: "Lamitube",
    packSize: "100g, 200 g",
  },
  {
    id: 23,
    productName: "Gloriday cream",
    uses: "For Skin tonner ",
    pack: "Lamitube",
    packSize: "10 g , 20 g",
  },
  {
    id: 24,
    productName: "Hemguard ointment",
    uses: "Anorectal ointment",
    pack: "Lamitube",
    packSize: "10 g , 20 g ,50g",
  },
  {
    id: 25,
    productName: "Painkyor Oil",
    uses: "Pain Management oil",
    pack: "Roll on",
    packSize: "10 ml",
  },
  {
    id: 26,
    productName: "Freshact Powder",
    uses: "Natural Bulk forming laxative",
    pack: "Sachet",
    packSize: "15 g",
  },
];
